In [2]:
# パッケージのインポート
from tensorflow.keras.datasets import boston_housing
from tensorflow.keras.layers import Activation, Dense, Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
# データセットの準備
(train_data, train_labels), (test_data, test_labels) = boston_housing.load_data()

65536/57026 [==================================] - 0s 1us/step


In [4]:
# データセットのシェイプの確認
print(train_data.shape)
print(train_labels.shape)
print(test_data.shape)
print(test_labels.shape)

(404, 13)
(404,)
(102, 13)
(102,)


In [5]:
# データセットのデータの確認
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE',  'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']
df = pd.DataFrame(train_data, columns=column_names)
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
0  1.23247   0.0   8.14   0.0  0.538  6.142   91.7  3.9769   4.0  307.0   
1  0.02177  82.5   2.03   0.0  0.415  7.610   15.7  6.2700   2.0  348.0   
2  4.89822   0.0  18.10   0.0  0.631  4.970  100.0  1.3325  24.0  666.0   
3  0.03961   0.0   5.19   0.0  0.515  6.037   34.5  5.9853   5.0  224.0   
4  3.69311   0.0  18.10   0.0  0.713  6.376   88.4  2.5671  24.0  666.0   

   PTRATIO       B  LSTAT  
0     21.0  396.90  18.72  
1     14.7  395.38   3.11  
2     20.2  375.52   3.26  
3     20.2  396.90   8.01  
4     20.2  391.43  14.65

In [6]:
# データセットのラベルの確認
print(train_labels[0:10])

[15.2 42.3 50.  21.1 17.7 18.5 11.3 15.6 15.6 14.4]


In [7]:
# データセットのシャッフルの前処理
order = np.argsort(np.random.random(train_labels.shape))
train_data = train_data[order]
train_labels = train_labels[order]

# データセットの正規化の前処理
mean = train_data.mean(axis=0)
std = train_data.std(axis=0)
train_data = (train_data - mean) / std
test_data = (test_data - mean) / std

In [8]:
# データセットの前処理後のデータの確認
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE',  'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']
df = pd.DataFrame(train_data, columns=column_names)
df.head()

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0 -0.104599 -0.483615  1.245881 -0.256833  2.677335 -1.924200  1.031652   
1 -0.381474 -0.483615 -0.207917 -0.256833  0.235976 -0.338664  0.383048   
2  1.116618 -0.483615  1.028326 -0.256833  0.338410  0.550026  1.110488   
3 -0.401231  0.695914  0.578516 -0.256833 -0.796907  0.246743 -0.552233   
4 -0.399056  1.201427 -1.448569 -0.256833 -1.095675  0.314453 -0.881910   

        DIS       RAD       TAX   PTRATIO         B     LSTAT  
0 -1.180831 -0.511142 -0.017443 -1.718189  0.448077  2.284044  
1 -0.612551 -0.396036 -0.089659  0.329446  0.448077  0.219332  
2 -1.091271  1.675886  1.565287  0.784476 -3.401612  1.170259  
3 -0.036677 -0.626249 -0.817836 -0.125584  0.427970 -0.632224  
4  2.491408 -0.971569 -0.426666  0.556961  0.448077 -0.933098

In [9]:
# モデルの作成
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(13,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(1))

2021-08-26 21:56:07.452071: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [10]:
# コンパイル
model.compile(loss='mse', optimizer=Adam(lr=0.001), metrics=['mae'])

/Users/kzyngkr/hobby/ML/ReinforcementLearning/venv/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


In [11]:
# EarlyStoppingの準備
early_stop = EarlyStopping(monitor='val_loss', patience=30)

In [12]:
# 学習
history = model.fit(train_data, train_labels, epochs=500, 
    validation_split=0.2, callbacks=[early_stop])

2021-08-26 21:56:07.664827: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/500
11/11 [==============================] - 1s 14ms/step - loss: 582.6155 - mae: 22.3911 - val_loss: 523.3795 - val_mae: 20.9783
Epoch 2/500
11/11 [==============================] - 0s 3ms/step - loss: 529.2142 - mae: 21.1995 - val_loss: 476.2919 - val_mae: 19.8200
Epoch 3/500
11/11 [==============================] - 0s 3ms/step - loss: 475.9618 - mae: 19.9268 - val_loss: 424.6620 - val_mae: 18.4835
Epoch 4/500
11/11 [==============================] - 0s 3ms/step - loss: 412.9955 - mae: 18.3614 - val_loss: 365.0248 - val_mae: 16.8136
Epoch 5/500
11/11 [==============================] - 0s 3ms/step - loss: 336.0103 - mae: 16.2933 - val_loss: 294.5912 - val_mae: 14.6487
Epoch 6/500
11/11 [==============================] - 0s 3ms/step - loss: 246.5042 - mae: 13.6509 - val_loss: 220.9033 - val_mae: 11.9899
Epoch 7/500
11/11 [==============================] - 0s 4ms/step - loss: 160.3648 - mae: 10.4963 - val_loss: 157.3005 - val_mae: 9.2019
Epoch 8/500
11/11 [======================

In [13]:
# グラフの表示
plt.plot(history.history['mean_absolute_error'], label='train mae')
plt.plot(history.history['val_mean_absolute_error'], label='val mae')
plt.xlabel('epoch')
plt.ylabel('mae [1000$]')
plt.legend(loc='best')
plt.ylim([0,5])
plt.show()

KeyError: 'mean_absolute_error'

In [ ]:
# 評価
test_loss, test_mae = model.evaluate(test_data, test_labels)
print('loss:{:.3f}\nmae: {:.3f}'.format(test_loss, test_mae))

102/102 [==============================] - 0s 80us/sample - loss: 15.8515 - mean_absolute_error: 2.5893
loss:15.851
mae: 2.589


In [ ]:
# 推論する値段の表示
print(np.round(test_labels[0:10]))

# 推論した値段の表示
test_predictions = model.predict(test_data[0:10]).flatten()
print(np.round(test_predictions))

[ 7. 19. 19. 27. 22. 24. 31. 23. 20. 23.]
[10. 19. 21. 33. 26. 21. 26. 22. 19. 22.]
